In [2]:
import numpy as np
from tqdm import tqdm

In [3]:
a = np.array([
    [0.0, 2.0, 1],
    [1.0, 2.0, 1],
    [2.0, 1.0, 1],
    [-3.0, 1.0, -1],
    [-2.0, -1.0, -1],
    [-3.0, -2.0, -1],
])

In [37]:
def sgt_seq_widrow_hoff(X, y, w, bias, b, eta, max_iter=100, theta=0):
    """Sequential Widrow-Hoff Learning

    Args:
        X (np.array): X variables
        y (np,array): label
        w (np.array): weight
        bias (float): bias value
        b (np.array): margin vector
        eta (float): learning rate
        max_iter (int): maximum number of iterations
    """
    i = 0
    converged = theta + 1
    res = []
    wb = np.concatenate((np.array([bias]), w))
    b = np.array(b)
    while i < max_iter: # and converged < theta:
        for j in range(len(y)):
            augX = np.concatenate(([1], X[j, :]))
            if y[j] == -1:
                augX = -augX
            yhat = wb.T @ augX
            byhat = (b[j] - yhat) * augX.T
            wb = wb + eta * byhat
            res.append((yhat, wb, byhat))
            i = i + 1
            converged = converged + np.abs(byhat)
    return res

In [34]:
res = sgt_seq_widrow_hoff(a[:, 1:3], a[:, 2], [0.0, 0.0], 1.0, [1.0, 0.5, 0.5, 0.5, 0.5, 1.0], 0.1, 20)

In [38]:
a = np.array([
    [0,0,1],
    [1,0,1],
    [2,1,1],
    [0,1,-1],
    [1,2,-1],
])

res = sgt_seq_widrow_hoff(a[:, 1:3], a[:, 2], [5,-1], -1.5, [2.0]*5, 0.2, 20)
res

[(-2.5, array([-0.6,  5. , -0.1]), array([4.5, 0. , 4.5])),
 (-0.7, array([-0.06,  5.  ,  0.44]), array([2.7, 0. , 2.7])),
 (5.380000000000001,
  array([-0.736,  4.324, -0.236]),
  array([-3.38, -3.38, -3.38])),
 (-3.824, array([-1.9008,  3.1592,  0.9288]), array([-5.824, -5.824,  5.824])),
 (-3.4887999999999995,
  array([-2.99856,  0.96368,  2.02656]),
  array([ -5.4888, -10.9776,   5.4888])),
 (-0.9720000000000004,
  array([-2.40416,  0.96368,  2.62096]),
  array([2.972, 0.   , 2.972])),
 (0.2168000000000001,
  array([-2.04752,  0.96368,  2.9776 ]),
  array([1.7832, 0.    , 1.7832])),
 (1.8937600000000003,
  array([-2.026272,  0.984928,  2.998848]),
  array([0.10624, 0.10624, 0.10624])),
 (4.040192,
  array([-1.6182336,  1.3929664,  2.5908096]),
  array([ 2.040192,  2.040192, -2.040192])),
 (1.4231103999999997,
  array([-1.73361152,  1.16221056,  2.70618752]),
  array([-0.5768896, -1.1537792,  0.5768896])),
 (0.9725760000000003,
  array([-1.52812672,  1.16221056,  2.91167232]),
  arr